<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<!-- Mobile Metas -->
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

	<!-- Site Metas -->
	<title>Mirai</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Site Icons -->
	<link rel="shortcut icon" href="#" type="image/x-icon" />
	<link rel="apple-touch-icon" href="#" />

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="css/bootstrap.min.css" />
	<!-- Pogo Slider CSS -->
	<link rel="stylesheet" href="css/pogo-slider.min.css" />
	<!-- Site CSS -->
	<link rel="stylesheet" href="css/style.css" />
	<!-- Responsive CSS -->
	<link rel="stylesheet" href="css/responsive.css" />
	<!-- Custom CSS -->
	<link rel="stylesheet" href="css/custom.css" />

	<!-- bootstrap core css -->
	<link rel="stylesheet" type="text/css" href="css1/bootstrap.css" />
	<!-- slider stylesheet -->
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />


	<!-- Custom styles for this template -->
	<link href="css1/style.css" rel="stylesheet" />
	<!-- responsive style -->
	<link href="css1/responsive.css" rel="stylesheet" />

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
	<!--additional method - for checkbox .. ,require_from_group method ...-->
	<script src="//jqueryvalidation.org/files/dist/additional-methods.min.js"></script>
	<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/localization/messages_zh_TW.js "></script>
	<style>
		#outer {
			background-color: #95afba;
			position: relative;
			/* ★ */
			height: 400px;
			display: flex;
			/* ★ */
			align-items: center;
			/* ★ */
		}

		.container {
			display: flex;
			justify-content: center;
			align-items: center;
		}

		.box1 {
			width:auto;
			padding: 10px;
			border: 1px gray;
			box-shadow: 3px 3px 9px gray;
			align-items: center;
		}

		.box2 {

			padding: 10px;
			border: 1px gray;
			box-shadow: 3px 3px 9px gray;
			height: 200px;
			border-radius: 10px 10px 10px 10px;

		}

		.label {
			width: 10%;
			padding: 0px;
			border: 1px gray;
			box-shadow: 3px 3px 9px gray;
			align-items: center;


		}


		.hr {


			width: 100%;

			border-top: 3px solid gray;
		}


		.column {
			align-items: center;

			width: 30%;
		}
	</style>





<body id="inner_page" data-spy="scroll" data-target="#navbar-wd" data-offset="98">

	<!-- LOADER -->
	<div id="preloader">
		<div class="loader">
			<img src="images/loader.gif" alt="#" />
		</div>
	</div>
	<!-- end loader -->
	<!-- END LOADER -->

	<?php include "header.php" ?>
	<!-- section -->

	<section class="inner_banner">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="full">
						<h3>校系介紹</h3>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- end section -->
	<br>
	<!-- section -->
	<div style="position:relative;left:21%">首頁/國立彰化師範大學/資訊工程學系</div>
	<br>
	<div class="container">
		<div class="box1">
			<br>


			<div class="col-xs-12">
				<h1> 🏫 國立彰化師範大學 資訊工程學系</h1>
				<hr class="hr">

				<div class="row">

					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
					<div class="column" style="display: inline-block; ">
						<div style="text-align:center">學費</div>
						<div class="box2" style="text-align:center;">
							<div style="font-size:70px;">💰</div>
							<div style="font-size:20px;">$20000</div>
						</div>
					</div>
					&nbsp&nbsp
					<div class="column" style="display: inline-block">
						<div style="text-align:center;">師生比</div>
						<div class="box2" style="position:relative;text-align:center;">
							<div style="font-size:70px;">👩🏻‍🏫</div>
							<div style="font-size:20px;">1:6</div>
						</div>
					</div>
					&nbsp&nbsp
					<div class="column" style="display: inline-block">
						<div style="text-align:center;">註冊率</div>
						<div class="box2" style="position:relative;text-align:center;">
							<div style="font-size:70px;">📋</div>
							<div style="font-size:20px;">98%</div>
						</div>
					</div>


				</div>

			</div>


			<br>
			<div class="col-xs-12">
				<h1>學校基本資料</h1>

				<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-left: auto; margin-right: auto; width:100%; ">
					<thead>
						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid; width:20%;" align=center cellpadding="8" border=1 colspan="11">創立時間</th>
							<th style="font-weight:300; border:1px #D4D4D4 solid;" cellpadding="8" border=1 colspan="20">1930年</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">全校學生人數</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid;" cellpadding="8" border=1 colspan="20">19250</td>
						</tr>
						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">科系學生人數</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid;" cellpadding="8" border=1 colspan="20">256</td>
						</tr>
						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">科系教師人數</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid;" cellpadding="8" border=1 colspan="20">20</td>
						</tr>
						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">新生住宿</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid; " cellpadding="4" colspan="20">



								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 男 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 女 </td>
											<td colspan="2">256人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 新生住宿比率 </td>
											<td colspan="2">98.5%</td>
										</tr>
									</thead>
								</table>
							</td>
						</tr>


						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">境外學生人數</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid; " cellpadding="4" colspan="20">



								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 學位生_正式修讀學位外國生 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 學位生_僑生(含港澳) </td>
											<td colspan="2">256人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 學位生_正式修讀學位陸生 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 非學位生_外國交換生 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 非學位生_外國短期研習及個人選讀 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 非學位生_大專附設華語文中心學生 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 非學位生_大陸研修生 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 非學位生_海青班 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 境外專班 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>
							</td>
						</tr>


						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">圖書館統計</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid; " cellpadding="4" colspan="20">



								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中文圖書收藏冊數(冊)-總類 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中文圖書收藏冊數(冊)-哲學類 </td>
											<td colspan="2">256人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中文圖書收藏冊數(冊)-宗教類 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中文圖書收藏冊數(冊)-科學類 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中文圖書收藏冊數(冊)-應用科學類 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中文圖書收藏冊數(冊)-社會科學類 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中文圖書收藏冊數(冊)-史地類 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中文圖書收藏冊數(冊)-語言文學類 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中文圖書收藏冊數(冊)-藝術類 </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 外文圖書收藏冊數(冊) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 期刊合訂本(未以圖書編目)(冊) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 光碟及其他類型資料庫(種) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 線上資料庫(種) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 電子期刊(種) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 電子書(種) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 視聽資料(件) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 圖書閱覽座位數(個) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 全年圖書(含視聽資料及其他館藏)借閱人次(人次) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 全年圖書(含視聽資料及其他館藏)借閱冊次(冊次) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 報紙(種) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 中.日文期刊(種) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 西文期刊(種) </td>
											<td colspan="2">123人</td>
										</tr>
									</thead>
								</table>
							</td>
						</tr>



						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">院系所及社團數</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid;" cellpadding="8" border=1 colspan="20">



								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 學院 </td>
											<td colspan="2">13</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 科系 </td>
											<td colspan="2">8</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom:1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 研究所 </td>
											<td colspan="2">78</td>
										</tr>
									</thead>
								</table>

								<table style=" font-size: 21px;border:2px #D4D4D4 solid; margin-top:2%; margin-bottom: 1%; margin-left:2%; margin-right: 2%; text-align:center; display:inline-block;">
									<thead>
										<tr>
											<td bgcolor=#F0F0F0 style="font-weight:700; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="3"> 社團數 </td>
											<td colspan="2">30</td>
										</tr>
									</thead>
								</table>


							</td>
						</tr>
						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">學校網址</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid;" cellpadding="8" border=1colspan="20"> csie@cc2.ncue.edu.tw</td>
						</tr>
						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">學校電話</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid;" cellpadding="8" border=1 colspan="20"> 04-7232105</td>
						</tr>
						<tr>
							<td bgcolor=#DFFFDF style="font-weight:300; border:1px #D4D4D4 solid;" align=center cellpadding="8" border=1 colspan="11">學校地址</td>
							<td style="font-weight:300; border:1px #D4D4D4 solid;" cellpadding="8" border=1 colspan="20"> 彰化縣彰化市進德路1號寶山校區</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<!-- end section -->
	<br>
	<?php include "footer.php" ?>

	<a href="#" id="scroll-to-top" class="hvr-radial-out"><i class="fa fa-angle-up"></i></a>

	<!-- ALL JS FILES -->
	<script src="js/jquery.min.js"></script>
	<script src="js/popper.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<!-- ALL PLUGINS -->
	<script src="js/jquery.magnific-popup.min.js"></script>
	<script src="js/jquery.pogo-slider.min.js"></script>
	<script src="js/slider-index.js"></script>
	<script src="js/smoothscroll.js"></script>
	<script src="js/form-validator.min.js"></script>
	<script src="js/contact-form-script.js"></script>
	<script src="js/isotope.min.js"></script>
	<script src="js/images-loded.min.js"></script>
	<script src="js/custom.js"></script>
	<script>
		/* counter js */

		(function($) {
			$.fn.countTo = function(options) {
				options = options || {};

				return $(this).each(function() {
					// set options for current element
					var settings = $.extend({}, $.fn.countTo.defaults, {
						from: $(this).data('from'),
						to: $(this).data('to'),
						speed: $(this).data('speed'),
						refreshInterval: $(this).data('refresh-interval'),
						decimals: $(this).data('decimals')
					}, options);

					// how many times to update the value, and how much to increment the value on each update
					var loops = Math.ceil(settings.speed / settings.refreshInterval),
						increment = (settings.to - settings.from) / loops;

					// references & variables that will change with each update
					var self = this,
						$self = $(this),
						loopCount = 0,
						value = settings.from,
						data = $self.data('countTo') || {};

					$self.data('countTo', data);

					// if an existing interval can be found, clear it first
					if (data.interval) {
						clearInterval(data.interval);
					}
					data.interval = setInterval(updateTimer, settings.refreshInterval);

					// initialize the element with the starting value
					render(value);

					function updateTimer() {
						value += increment;
						loopCount++;

						render(value);

						if (typeof(settings.onUpdate) == 'function') {
							settings.onUpdate.call(self, value);
						}

						if (loopCount >= loops) {
							// remove the interval
							$self.removeData('countTo');
							clearInterval(data.interval);
							value = settings.to;

							if (typeof(settings.onComplete) == 'function') {
								settings.onComplete.call(self, value);
							}
						}
					}

					function render(value) {
						var formattedValue = settings.formatter.call(self, value, settings);
						$self.html(formattedValue);
					}
				});
			};

			$.fn.countTo.defaults = {
				from: 0, // the number the element should start at
				to: 0, // the number the element should end at
				speed: 1000, // how long it should take to count between the target numbers
				refreshInterval: 100, // how often the element should be updated
				decimals: 0, // the number of decimal places to show
				formatter: formatter, // handler for formatting the value before rendering
				onUpdate: null, // callback method for every time the element is updated
				onComplete: null // callback method for when the element finishes updating
			};

			function formatter(value, settings) {
				return value.toFixed(settings.decimals);
			}
		}(jQuery));

		jQuery(function($) {
			// custom formatting example
			$('.count-number').data('countToOptions', {
				formatter: function(value, options) {
					return value.toFixed(options.decimals).replace(/\B(?=(?:\d{3})+(?!\d))/g, ',');
				}
			});

			// start all the timers
			$('.timer').each(count);

			function count(options) {
				var $this = $(this);
				options = $.extend({}, options || {}, $this.data('countToOptions') || {});
				$this.countTo(options);
			}
		});
	</script>
</body>

</html>